version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "80:8080"
    environment:
      REDIS_URL: $REDIS_URL
      POSTGRES_URL: $POSTGRES_URL
    depends_on:
      - redis
      - postgres
    networks:
      - app-network-collector
networks:
  app-network-collector:
    driver: bridge
