<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Animal extends Model
{
    use HasFactory;
    protected $fillable = [
        'uuid',
        'name',
        'number',
        'organisation_id',
        'birthday',
        'breed_id',
        'number_rshn',
        'bolus_id',
        'number_rf',
        'number_tavro',
        'number_tag',
        'tag_color',
        'number_collar',
        'status_id',
        'sex',
        'withdrawn_at',
    ];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->uuid = Str::uuid();
        });
    }

    public function organisation():BelongsTo
    {
        return $this->belongsTo(Organisation::class);
    }

    public function breed():BelongsTo
    {
        return $this->belongsTo(Breed::class);
    }
}
