<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Animal extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->uuid = Str::uuid();
        });
    }

    public function organisation():BelongsTo
    {
        return $this->belongsTo(Organisation::class);
    }
}
