<?php

namespace App\Models;

use AllowDynamicProperties;
use App\Models\Event\EventInterface;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

#[AllowDynamicProperties] class Event extends Model implements EventInterface
{
    use HasFactory;
    protected $fillable = [
        'event_type_id',
        'type',
        'data',
        'event_category',
    ];
    protected $table = 'events';

    protected $casts = [
        'data' => 'array',
        'data.is_inseminated' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->creator_id = auth()->id();
        });
    }

    public function data(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => $value ? collect(json_decode($value, true)) : null,
            set: fn ($value) => $value ? json_encode($value) : null,
        );
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id', 'id');
    }

    public function eventType(): BelongsTo
    {
        return $this->belongsTo(EventType::class, 'event_type_id', 'id');
    }

}
